version: '3.9'
services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: dksdlfduq2
            MYSQL_DATABASE: mobiusdb
        command: --default-authentication-plugin=mysql_native_password
        # ports:
        #     - 3306:3306
        # network_mode: host
        volumes:
            - mobius-data:/var/lib/mysql
            - ./Mobius/mobius/mobiusdb.sql:/docker-entrypoint-initdb.d/mobiusdb.sql
        restart: always
        healthcheck:   # It is a function of Docker-compose to check whether the software is working or not.
            test: ["CMD", "mysqladmin" , "--password=dksdlfduq2", "ping"]
            interval: 20s
            timeout: 20s
            retries: 10
    
    node-app:
        build: .
        # network_mode: host
        ports:
            - 8200:7579
        depends_on:
            db:
                condition: service_healthy
        restart: always

    # mosquitto-broker:
    #     image: eclipse-mosquitto:latest  # Import the mosquitto (MQTT Tool) image stored in the Docker-Hub.
    #     # ports:
    #         # - 1883:1883
    #     network_mode: "host"
    #     volumes:
    #         - ./etc/mosquitto:/etc/mosquitto:ro
    #         - ./var/log/mosquitto:/var/log/mosquitto:rw
    #     depends_on:   # Mosquitto will work after mysql is running. If this is not taken into consideration, the delay with Mobius will not work properly.
    #         db:
    #             condition: service_healthy

volumes:
  mobius-data: